; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
core_dir = .pio_core

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
; Workaround for PlatformIO resolving riscv toolchain to a wrong namespace.
platform_packages =
    platformio/toolchain-riscv32-esp@14.2.0+20241119
board_upload.flash_size = 16MB
board_build.psram_size = 8MB
board_build.partitions = partitions.csv
upload_speed = 115200
monitor_speed = 115200

; SDK Config - local file overrides defaults
board_build.sdkconfig_defaults = 
    sdkconfig.defaults

; Scripts for SR models and runtime NVS settings
extra_scripts =
    pre:tools/generate_srmodels.py
    pre:tools/generate_nvs_settings.py
    post:tools/add_srmodels_image.py
    post:tools/flash_srmodels.py
    post:tools/flash_nvs_settings.py

; Flash models to the model partition (0x610000)
board_upload.flash_extra_images =
    0x610000 .pio/build/${PIOENV}/srmodels/srmodels.bin
